# This is workflow name

name: Hello

on: 
  push: 
     branches: [main]

# There are jobs inside the workflow 

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hellow to users
        run: echo "Hellow"
    
      - name: Say hellow to username
        run: echo "Hellow $USER"
