# Docker file

name: Hello
on:
  workflow_dispatch: 
    inputs:
      environmets:
        description: This is the environments value where this values workflow runs
        default: dev 
        type: choice
        options:
           - dev
           - prod
           - staging
  

jobs:
  code:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
        run: echo "code clone from GitHub" 
  build:
     needs: [code]
     runs-on: ubuntu-latest
     steps:
       - name: Build Docker Container
         run: echo "Docker Container build" 

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
       - name: Test the container
         run: echo "Testing the container"

  deploy:
     needs: [build,test]
     runs-on: ubuntu-latest
     steps:
     - name: Deploying the app
       run: echo "Docker compose deployed on the server"
