name: Portfolio

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions: 
  pages: write
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # Get Access to your Portfolio code via a pre-built action
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup GitHub Pages
      - name: Setup Github Pages
        uses: actions/configure-pages@v4

      # Package and upload static code artifacts
      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          # If your files are in a subfolder like 'dist' or 'public', change '.' to './dist'
          path: '.' 

      # Deploy the uploaded artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
